import Head from "next/head";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import Menubar from "./components/menubar/menubar";
config.autoAddCss = false;
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Menubar />
        {children}
      </body>
    </html>
  );
}
